### ISSUE TITLE
Please release for jade

### ISSUE THREAD

**Issue by scpeters** [ros-planning/random_numbers#9]
Thanks!

**Comment by scpeters** [comment]
https://github.com/ros-planning/geometric_shapes/issues/27

**Comment by wjwwood** [comment]
+1

**Comment by wjwwood** [comment]
@davetcoleman looks like you did a release of this last, do you want to take care of the jade release or can I?

**Comment by wjwwood** [comment]
@davetcoleman I'm going to go ahead and release this since there are no outstanding issues or pull requests. Hopefully that's all right, normally I wouldn't but it blocking quite a bit of otherwise ready stuff.

**Comment by wjwwood** [comment]
https://github.com/ros/rosdistro/pull/8079
